### ISSUE TITLE
Audio Not Playing In iOS but changes AudioStates

### ISSUE THREAD

**Issue by lekeCoder** [idofilus/flutter_audio#26]
Hello, 

I implemented this plugin in my flutter app and it plays audio downloaded to the device in Android but not in iOS.  In iOS device, it will change AudioState but does not play out irrespective of the volume.
What can I do?

**Comment by mr-52hz** [comment]
> Hello,
> 
> I implemented this plugin in my flutter app and it plays audio downloaded to the device in Android but not in iOS. In iOS device, it will change AudioState but does not play out irrespective of the volume.
> What can I do?

Have you solved it？How?

**Comment by HugoHeneault** [comment]
I have the same issue, on some devices it's working (ie iPhone SE) on other it doesn't (ie. iPhone 6)

Any ideas?

**Comment by HugoHeneault** [comment]
So I solved it by adding

```
   <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
```

To my main `Info.plist` file

**Comment by mr-52hz** [comment]
thank you very much!

**Comment by lekeCoder** [comment]
> So I solved it by adding
> 
> ```
>    <key>NSAppTransportSecurity</key>
>     <dict>
>         <key>NSAllowsArbitraryLoads</key>
>         <true/>
>     </dict>
> ```
> 
> To my main `Info.plist` file

I solved this problem by using another package which did not require me to change my `info.plist` file. You can check the package here https://pub.dev/packages/audio#-readme-tab-
